enum modelnums {
	model_mediumhulk = -1,
	model_mediumlifter = -1,
	model_spider = -1,
	model_class1drone = -1,
	model_class2drone = -1,
	model_class1driller_cloaked = -1,
	model_mediumhulk_cloaked = -1,
	model_class2supervisor = -1,
	model_secondarylifter = -1,
	model_class1heavydriller = -1,
	model_class3gopher = -1,
	model_class1platform = -1,
	model_class2platform = -1,
	model_splitter = -1,
	model_smallspider = -1,
	model_fusionhulk = -1,
	model_superhulk = -1,
	model_d1boss1 = -1,
	model_cloakedlifter = -1,
	model_class1driller = -1,
	model_smallhulk = -1,
	model_advancedlifter = -1,
	model_ptmcdefense = -1,
	model_d1boss2 = -1,
	model_reactord1 = -1,
	model_reactord1_destr = -1,
	model_exit01 = -1,
	model_exit01_destr = -1,
	model_pyrogl_destr = -1,
	model_laser1_outer = -1,
	model_laser1_lod = -1,
	model_laser1_lod2 = -1,
	model_laser1_inner = -1,
	model_laser2_outer = -1,
	model_laser2_lod = -1,
	model_laser2_lod2 = -1,
	model_laser2_inner = -1,
	model_laser3_outer = -1,
	model_laser3_lod = -1,
	model_laser3_lod2 = -1,
	model_laser3_inner = -1,
	model_laser4_outer = -1,
	model_laser4_lod = -1,
	model_laser4_lod2 = -1,
	model_laser4_inner = -1,
	model_flare = -1,
	model_botlas3_outer = -1,
	model_botlas3_inner = -1,
	model_fusion_outer = -1,
	model_fusion_inner = -1,
	model_botlas1_outer = -1,
	model_botlas1_inner = -1,
	model_botlas4_outer = -1,
	model_botlas4_inner = -1,
	model_bper = -1,
	model_smelter = -1,
	model_icespindle = -1,
	model_bulkdestroyer = -1,
	model_trnracer = -1,
	model_foxattackbot = -1,
	model_sidearm = -1,
	model_redfattyboss = -1,
	model_newboss = -1,
	model_guidebot = -1,
	model_mineguard = -1,
	model_eviltwin = -1,
	model_itscbot = -1,
	model_itdbot = -1,
	model_pestbot = -1,
	model_pigbot = -1,
	model_diamondclaw = -1,
	model_hornet = -1,
	model_thiefbot = -1,
	model_seeker = -1,
	model_ebandit = -1,
	model_fireboss = -1,
	model_waterboss = -1,
	model_boarshead = -1,
	model_d2spider = -1,
	model_omegadefensespawn = -1,
	model_sidearmmodula = -1,
	model_louguard = -1,
	model_alien1boss = -1,
	model_popcornminiboss = -1,
	model_cloakeddiamondclaw = -1,
	model_cloakedsmelter = -1,
	model_guppy = -1,
	model_smelterclone = -1,
	model_omegadefensespawnclone = -1,
	model_bperbotclone = -1,
	model_spiderclone = -1,
	model_spawn = -1,
	model_iceboss = -1,
	model_spawnclone = -1,
	model_alien2boss = -1,
	model_minireactor = -1,
	model_alien2reactor = -1,
	model_alien2reactor_destr = -1,
	model_groupareactor = -1,
	model_groupareactor_destr = -1,
	model_waterreactor = -1,
	model_waterreactor_destr = -1,
	model_firerreactor = -1,
	model_firereactor_destr = -1,
	model_alien1reactor = -1,
	model_alien1reactor_destr = -1,
	model_icereactor = -1,
	model_icereactor_destr = -1,
	model_marker = -1,
	model_laser5_outer = -1,
	model_laser5_lod = -1,
	model_laser5_lod2 = -1,
	model_laser5_inner = -1,
	model_laser6_outer = -1,
	model_laser6_lod = -1,
	model_laser6_lod2 = -1,
	model_laser6_inner = -1,
	model_flashmsl = -1,
	model_guidedmsl = -1,
	model_mercurymsl = -1,
	model_earthshaker = -1,
	model_botvulcan = -1,
	model_botlas6_outer = -1,
	model_botlas6_inner = -1,
	model_mine = -1,
	model_earthshakerchild = -1,
	model_pyrogl = 0,
	model_concussion,
	model_homer,
	model_smartmsl,
	model_mega,
};

const char *xmodelnames[] = {
	"pyrogl.ase",
	"concussion.ase",
	"homer.ase",
	"smartmsl.ase",
	"mega.ase"
};

#define NUM_XMODELS ((int)(sizeof(xmodelnames) / sizeof(xmodelnames[0])))

short xmodel_xlate[] = {
	model_mediumhulk,
	model_mediumhulk,
	model_mediumlifter,
	model_mediumlifter,
	model_spider,
	model_spider,
	model_class1drone,
	model_class1drone,
	model_class2drone,
	model_class2drone,
	model_class1driller_cloaked,
	model_class1driller_cloaked,
	model_mediumhulk_cloaked,
	model_mediumhulk_cloaked,
	model_class2supervisor,
	model_secondarylifter,
	model_secondarylifter,
	model_class1heavydriller,
	model_class1heavydriller,
	model_class3gopher,
	model_class1platform,
	model_class2platform,
	model_splitter,
	model_smallspider,
	model_smallspider,
	model_fusionhulk,
	model_superhulk,
	model_superhulk,
	model_d1boss1,
	model_cloakedlifter,
	model_cloakedlifter,
	model_class1driller,
	model_class1driller,
	model_smallhulk,
	model_smallhulk,
	model_advancedlifter,
	model_advancedlifter,
	model_ptmcdefense,
	model_ptmcdefense,
	model_d1boss2,
	model_bper,
	model_smelter,
	model_smelter,
	model_icespindle,
	model_bulkdestroyer,
	model_trnracer,
	model_foxattackbot,
	model_sidearm,
	model_sidearm,
	model_redfattyboss,
	model_newboss,
	model_guidebot,
	model_mineguard,
	model_mineguard,
	model_eviltwin,
	model_itscbot,
	model_itdbot,
	model_itdbot,
	model_pestbot,
	model_pestbot,
	model_pigbot,
	model_pigbot,
	model_diamondclaw,
	model_diamondclaw,
	model_hornet,
	model_thiefbot,
	model_thiefbot,
	model_seeker,
	model_ebandit,
	model_fireboss,
	model_waterboss,
	model_boarshead,
	model_d2spider,
	model_omegadefensespawn,
	model_sidearmmodula,
	model_louguard,
	model_alien1boss,
	model_popcornminiboss,
	model_cloakeddiamondclaw,
	model_cloakeddiamondclaw,
	model_cloakedsmelter,
	model_cloakedsmelter,
	model_guppy,
	model_smelterclone,
	model_smelterclone,
	model_omegadefensespawnclone,
	model_bperbotclone,
	model_spiderclone,
	model_spawn,
	model_iceboss,
	model_spawnclone,
	model_alien2boss,
	model_minireactor,
	model_reactord1,
	model_reactord1_destr,
	model_alien2reactor,
	model_alien2reactor_destr,
	model_groupareactor,
	model_groupareactor_destr,
	model_waterreactor,
	model_waterreactor_destr,
	model_firerreactor,
	model_firereactor_destr,
	model_alien1reactor,
	model_alien1reactor_destr,
	model_icereactor,
	model_icereactor_destr,
	model_marker,
	model_pyrogl,
	model_pyrogl,
	model_pyrogl_destr,
	model_laser1_outer,
	model_laser1_lod,
	model_laser1_lod2,
	model_laser1_inner,
	model_laser2_outer,
	model_laser2_lod,
	model_laser2_lod2,
	model_laser2_inner,
	model_laser3_outer,
	model_laser3_lod,
	model_laser3_lod2,
	model_laser3_inner,
	model_laser4_outer,
	model_laser4_lod,
	model_laser4_lod2,
	model_laser4_inner,
	model_concussion,
	model_flare,
	model_botlas3_outer,
	model_botlas3_inner,
	model_fusion_outer,
	model_fusion_inner,
	model_homer,
	model_smartmsl,
	model_mega,
	model_homer,
	model_concussion,
	model_botlas1_outer,
	model_botlas1_inner,
	model_botlas4_outer,
	model_botlas4_inner,
	model_mega,
	model_laser5_outer,
	model_laser5_lod,
	model_laser5_lod2,
	model_laser5_inner,
	model_laser6_outer,
	model_laser6_lod,
	model_laser6_lod2,
	model_laser6_inner,
	model_flashmsl,
	model_guidedmsl,
	model_mercurymsl,
	model_earthshaker,
	model_botvulcan,
	model_botlas6_outer,
	model_botlas6_inner,
	model_flashmsl,
	model_mine,
	model_earthshakerchild,
	model_mercurymsl,
	model_smartmsl,
	model_earthshaker,
	model_earthshakerchild,
	model_flashmsl
};