enum modelnums {
	model_mediumhulk = -1,
	model_mediumlifter = -1,
	model_spider = -1,
	model_class1drone = -1,
	model_class2drone = -1,
	model_class1driller_cloaked = -1,
	model_mediumhulk_cloaked = -1,
	model_class2supervisor = -1,
	model_secondarylifter = -1,
	model_class1heavydriller = -1,
	model_class3gopher = -1,
	model_class1platform = -1,
	model_class2platform = -1,
	model_splitter = -1,
	model_smallspider = -1,
	model_fusionhulk = -1,
	model_superhulk = -1,
	model_d1boss1 = -1,
	model_cloakedlifter = -1,
	model_class1driller = -1,
	model_smallhulk = -1,
	model_advancedlifter = -1,
	model_ptmcdefense = -1,
	model_d1boss2 = -1,
	model_reactord1 = -1,
	model_reactord1_destr = -1,
	model_exit01 = -1,
	model_exit01_destr = -1,
	model_pyrogl_destr = -1,
	model_laser1_lod = -1,
	model_laser1_lod2 = -1,
	model_laser1_inner = -1,
	model_laser2_lod = -1,
	model_laser2_lod2 = -1,
	model_laser2_inner = -1,
	model_laser3_lod = -1,
	model_laser3_lod2 = -1,
	model_laser3_inner = -1,
	model_laser4_lod = -1,
	model_laser4_lod2 = -1,
	model_laser4_inner = -1,
	model_flare = -1,
	model_botlas3_outer = -1,
	model_botlas3_inner = -1,
	model_fusion_inner = -1,
	model_botlas1_outer = -1,
	model_botlas1_inner = -1,
	model_botlas4_outer = -1,
	model_botlas4_inner = -1,
	model_pyrogl = 0,
	model_concussion,
	model_homer,
	model_smartmsl,
	model_mega,
	model_fusion_outer,
	model_laser1_outer,
	model_laser2_outer,
	model_laser3_outer,
	model_laser4_outer,
	model_pow_extralife,
	model_pow_laser,
	model_pow_vulcan,
	model_pow_spreadfire,
	model_pow_plasma,
	model_pow_fusion,
	model_pow_pminepack,
	model_weapon_proxmine,
	model_pow_concussion4,
	model_pow_homer4,
	model_pow_quadlaser,
	model_pow_cloak,
	model_pow_invul,
	model_pow_bluekey,
	model_pow_redkey,
	model_pow_goldkey,
	model_pow_vulcanammo
};

const char *xmodelnames[] = {
	"pyrogl.ase",
	"concussion.ase",
	"homer.ase",
	"smartmsl.ase",
	"mega.ase",
	"fusionblob.ase",
	"laser1.ase",
	"laser2.ase",
	"laser3.ase",
	"laser4.ase",
	"extralife.ase",
	"laser.ase",
	"vulcan.ase",
	"spreadfire.ase",
	"plasma.ase",
	"fusion.ase",
	"pminepack.ase",
	"proxmine.ase",
	"concussion4.ase",
	"homer4.ase",
	"quadlaser.ase",
	"cloak.ase",
	"invul.ase",
	"bluekey.ase",
	"redkey.ase",
	"goldkey.ase",
	"vulcanammo.ase",
	"concussion.ase",
	"homer.ase",
	"smartmsl.ase",
	"mega.ase"
};

#define NUM_XMODELS ((int)(sizeof(xmodelnames) / sizeof(xmodelnames[0])))

short xmodel_polyobj_xlate[] = {
	model_mediumhulk,
	model_mediumhulk,
	model_mediumlifter,
	model_spider,
	model_spider,
	model_class1drone,
	model_class1drone,
	model_class2drone,
	model_class2drone,
	model_class1driller_cloaked,
	model_class1driller_cloaked,
	model_mediumhulk_cloaked,
	model_mediumhulk_cloaked,
	model_class2supervisor,
	model_secondarylifter,
	model_secondarylifter,
	model_class1heavydriller,
	model_class1heavydriller,
	model_class3gopher,
	model_class1platform,
	model_class2platform,
	model_splitter,
	model_smallspider,
	model_smallspider,
	model_fusionhulk,
	model_superhulk,
	model_superhulk,
	model_d1boss1,
	model_cloakedlifter,
	model_cloakedlifter,
	model_class1driller,
	model_class1driller,
	model_smallhulk,
	model_smallhulk,
	model_advancedlifter,
	model_advancedlifter,
	model_ptmcdefense,
	model_ptmcdefense,
	model_d1boss2,
	model_reactord1,
	model_reactord1_destr,
	model_exit01,
	model_exit01_destr,
	model_pyrogl,
	model_pyrogl,
	model_pyrogl_destr,
	model_laser1_outer,
	model_laser1_lod,
	model_laser1_lod2,
	model_laser1_inner,
	model_laser2_outer,
	model_laser2_lod,
	model_laser2_lod2,
	model_laser2_inner,
	model_laser3_outer,
	model_laser3_lod,
	model_laser3_lod2,
	model_laser3_inner,
	model_laser4_outer,
	model_laser4_lod,
	model_laser4_lod2,
	model_laser4_inner,
	model_concussion,
	model_flare,
	model_botlas3_outer,
	model_botlas3_inner,
	model_fusion_outer,
	model_fusion_inner,
	model_homer,
	model_smartmsl,
	model_mega,
	model_homer,
	model_concussion,
	model_botlas1_outer,
	model_botlas1_inner,
	model_botlas4_outer,
	model_botlas4_inner,
	model_mega
};

enum {
	model_pow_energy = -1,
	model_pow_shield = -1,
	model_pow_radar_robots = -1,
	model_pow_radar_powerups = -1,
	model_pow_full_map = -1,
	model_pow_turbo = -1,
	model_pow_headlight = -1,
	model_pow_megawow = -1
};

short xmodel_powerup_xlate[] = {
	model_pow_extralife,
	model_pow_energy,
	model_pow_shield,
	model_pow_laser,
	model_pow_bluekey,
	model_pow_redkey,
	model_pow_goldkey,
	model_pow_radar_robots,
	model_pow_radar_powerups,
	model_pow_full_map,
	model_concussion,
	model_pow_concussion4,
	model_pow_quadlaser,
	model_pow_vulcan,
	model_pow_spreadfire,
	model_pow_plasma,
	model_pow_fusion,
	model_pow_pminepack,
	model_homer,
	model_pow_homer4,
	model_smartmsl,
	model_mega,
	model_pow_vulcanammo,
	model_pow_cloak,
	model_pow_turbo,
	model_pow_invul,
	model_pow_headlight,
	model_pow_megawow
};
