name: Package - Windows

on:
  #push:
  #  branches: [ master ]

  #pull_request:
  #  branches: [ master ]

  workflow_dispatch:

  workflow_call:

jobs:
  windows:
    name: Windows
    runs-on: windows-2019

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            git
            zip
            base-devel 
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-pkgconf
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-physfs
            mingw-w64-x86_64-SDL
            mingw-w64-x86_64-SDL_mixer
            mingw-w64-x86_64-libpng
            mingw-w64-x86_64-glew
            mingw-w64-x86_64-ntldd-git

      - name: Clone repository
        uses: actions/checkout@v3

      - name: Configure D1
        run: cmake -S d1 -B buildd1 -DCMAKE_BUILD_TYPE=RelWithDebInfo

      - name: Build D1
        run: cmake --build buildd1 

      - name: Configure D2
        run: cmake -S d2 -B buildd2 -DCMAKE_BUILD_TYPE=RelWithDebInfo

      - name: Build D2
        run: cmake --build buildd2

      - name: Package
        run: ./contrib/packaging/windows/build_package.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: '*.zip'
